
const teacherYear = {
  "Dawn Crisologo":"FYP","Carmina Dalida":"FYP","Jerrica Alzate-Gunda":"FYP",
  "Lovelyn Balbedina":"FYP", "Mara Esguerra":"FYP","Jayson Bingcang":"FYP",
  "Maria Capundag":"FYP","Lodivina Pabello":"FYP",
  "Jonathan Javier":"FYP","Recel Calaunan":"FYP","Edwin Del Rosario":"FYP","Sheila Fernandez":"FYP",
  "Liz Saguico":"FYP",
  "China De Vera":"FYP","Lerma Espina":"FYP","Mike Aloba":"FYP","Rey Nino Baguio":"FYP","Princess Casa":"FYP","Bernard Llaguno":"FYP",
  "Yna Mongcal":"FYP","Deanne Zambrano":"FYP",  "Franel Infante": "FYP",
  "Mardan Llanura": "FYP",
  "Louvelle Parulan": "FYP",
  "Pao Apolinario": "FYP & SYP",
  "Melodee Pacio": "FYP",
  "Karlo Kristobal": "FYP",
   "Lieza Crisostomo": "FYP",
  "Maria Torralba": "FYP",
    "Maria Bartolay": "FYP & SYP",   
  "Glenn Espino": "FYP & AYP",     
  "Arnold Lapuz": "FYP",           
  "Erin Dela Cruz": "FYP",         
  "Kim Favor": "FYP & AYP",   
   "Renan Ortiz": "FYP",
  "Ervin Santos": "FYP",
  "Boon Lauw": "FYP",
  "Monica Xavier": "FYP",
  "Hati Callo":"FYP",
    "Fil Teodoro":"FYP",
    "Tolits Englatera":"FYP",
    "Melody Hernandez":"FYP",
    "Eileen Sarmago":"FYP",
    "Natalie Basquez":"FYP",
    "Jane Turingan":"FYP",



  "Neil Ramirez":"AYP","Maria Pinlac":"AYP","Melanie Cheng":"AYP",
  "Aileen Dela Cruz":"AYP","Kris Aquino":"AYP", "Lester Mendoza":"AYP", "Kat Villar":"AYP",
  "Joseph Estrella":"AYP", "Roy Canseco":"AYP", "Aline Mendoza":"AYP","Phillip Lim":"AYP",
  "Mark Tarcelo":"AYP","Joanna Soriano":"AYP","Jez Ambrocio":"AYP","Benigno Montemayor":"AYP",
  "Kornellie Raquitico":"AYP","Camille Barquilla":"AYP",
  "Simoun Monzon":"AYP","Ligaya Cion":"AYP","Francis Orque":"AYP",  "Kiel Granada": "AYP",
  "Mary Magpantay": "AYP",
  "Von Chua": "AYP",
  "Diane Estonilo": "AYP",
  "Darlene Gustilo": "AYP",
  "Jayson Palomar": "AYP",
  "Fortunato Tacuboy": "AYP & SYP",
  "Neil Bartolay": "AYP",
  "Anna Bonifacio": "AYP",
  "Marvice Ong": "AYP",
  "Hazel Manuel": "AYP",
   "Charles De Guzman": "AYP",      
  "Diana Sarenas": "AYP",         
    "Rose Mary Butaran": "AYP",
  "Ana Chupungco": "AYP",
  "Kresta David": "AYP",
  "Benedict Mendoza": "AYP",
    "Ryan Cruz": "AYP",
      "JM Alvarez": "AYP",
        "Robert Duliesco": "AYP",
  "Jennifer Balangue": "AYP",
    "Florides Anda": "AYP",

      "Dianmar Briones": "AYP",
  "Maybeline Pacia": "AYP",






  "Christian Abagat":"SYP","Rieziel Bernal":"SYP",
  "Ralph Hipolito":"SYP","Danah Purificacion":"SYP","Chuckie Calsado":"SYP","Felipe Del Castillo":"SYP",
  "Justin Guce":"SYP","Dinnie Morales":"SYP", "Azlek Tan":"SYP",
  "Leonel Po":"SYP","Xandra Razonabe":"SYP","Arianne Won":"SYP","Edge Angeles":"SYP","Kim De Castro":"SYP",
  "Jennifer Bermudez":"SYP","Eric Nebran":"SYP","Christine Aguila":"SYP","Mark Lopez":"SYP","Lilibeth Quiore":"SYP","name":"SYP",
    "Mark Ayaay": "SYP",
  "Faith Daguman": "SYP",
  "Petri Espanol": "SYP",
    "Justin Alvarez": "SYP",
  "Bimbo Galit": "SYP",
  "Gerold Pedemonte": "SYP",
  "Bhazel Pelicano": "SYP",
  "Marc Perez": "SYP",
  "John Pingol": "SYP",
   "Vladmir Lopez": "SYP",          
  "Bambie Untalan-Mina": "SYP",    
  "Sarah Eisma": "SYP",
    "Restituto Cortez": "SYP",
  "Elijah Estante": "SYP",
  "Donna Hipolito": "SYP",
  "Elliard Yanza": "SYP",
  "Catherine Dela Cruz": "SYP",
  "Alangelico San Pascual": "SYP",
  "Mc Villaruel": "SYP",
  "Andrei Castro": "SYP",
  "Zebastian Dogma": "SYP",
  "John Carlo Elopre": "SYP",
  "Marivic Morata": "SYP",
    "Jason Alcarez": "SYP",
  "Jejomar Bongat": "SYP",
  "Ana Carvajal": "SYP",

  "Efren Paz": "FYP & SYP","John Wyson":"FYP & SYP", "Mary Dino":"FYP & SYP", "Flordeliza Fermin":"FYP & SYP",
  "Mark Tarcelo": "FYP & AYP", "Nico Orduna": "FYP & AYP", 
  "Edwin De Ocampo ": "AYP & SYP", "Joseph Estrella": "AYP & SYP", "Sarah Napoles": "AYP & SYP",  "Kim Gargar": "AYP & SYP"

};
